# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be5465b54a3e184bcc582f670371957f"
name = "app-demo"
application_url = "https://routers-beaches-consumers-harbor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gold-evermore.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://routers-beaches-consumers-harbor.trycloudflare.com/auth/callback",
  "https://routers-beaches-consumers-harbor.trycloudflare.com/auth/shopify/callback",
  "https://routers-beaches-consumers-harbor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
